global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Serilog;
global using AutoMapper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Security.Claims;
global using Model = API.Domain.Models;
global using MyEnum = API.Resources.Enums;
global using API.Domain.Contexts;
